name: PlatformIO Build Check for microros

on:
  push:
    branches:
      - microros  # Trigger only on pushes to the microros branch
  pull_request:
    branches:
      - microros  # Trigger only on pull requests targeting the microros branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  # Replace with a compatible version for PlatformIO

      # Install PlatformIO
      - name: Install PlatformIO
        run: |
          python -m pip install --upgrade pip
          pip install platformio

      # Build the project
      - name: Build with PlatformIO
        run: |
          platformio run
