name: PlatformIO CI

on:
  push:
    branches: [noetic]
  pull_request:
    branches: [noetic]
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # 4 AM Montreal time

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: |
          cd pio_workspace
          pio run
